// Generated by gencpp from file datashow/Pose_error.msg
// DO NOT EDIT!


#ifndef DATASHOW_MESSAGE_POSE_ERROR_H
#define DATASHOW_MESSAGE_POSE_ERROR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace datashow
{
template <class ContainerAllocator>
struct Pose_error_
{
  typedef Pose_error_<ContainerAllocator> Type;

  Pose_error_()
    : linear_e(0.0)
    , angle_e(0.0)  {
    }
  Pose_error_(const ContainerAllocator& _alloc)
    : linear_e(0.0)
    , angle_e(0.0)  {
  (void)_alloc;
    }



   typedef double _linear_e_type;
  _linear_e_type linear_e;

   typedef double _angle_e_type;
  _angle_e_type angle_e;





  typedef boost::shared_ptr< ::datashow::Pose_error_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::datashow::Pose_error_<ContainerAllocator> const> ConstPtr;

}; // struct Pose_error_

typedef ::datashow::Pose_error_<std::allocator<void> > Pose_error;

typedef boost::shared_ptr< ::datashow::Pose_error > Pose_errorPtr;
typedef boost::shared_ptr< ::datashow::Pose_error const> Pose_errorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::datashow::Pose_error_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::datashow::Pose_error_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace datashow

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'datashow': ['/home/hyuk/roswork/workspace1/src/datashow/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::datashow::Pose_error_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::datashow::Pose_error_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::datashow::Pose_error_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::datashow::Pose_error_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::datashow::Pose_error_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::datashow::Pose_error_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::datashow::Pose_error_<ContainerAllocator> >
{
  static const char* value()
  {
    return "11596aec3b6d70c9624c2fe748bd31cb";
  }

  static const char* value(const ::datashow::Pose_error_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x11596aec3b6d70c9ULL;
  static const uint64_t static_value2 = 0x624c2fe748bd31cbULL;
};

template<class ContainerAllocator>
struct DataType< ::datashow::Pose_error_<ContainerAllocator> >
{
  static const char* value()
  {
    return "datashow/Pose_error";
  }

  static const char* value(const ::datashow::Pose_error_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::datashow::Pose_error_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 linear_e\n"
"float64 angle_e\n"
;
  }

  static const char* value(const ::datashow::Pose_error_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::datashow::Pose_error_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.linear_e);
      stream.next(m.angle_e);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Pose_error_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::datashow::Pose_error_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::datashow::Pose_error_<ContainerAllocator>& v)
  {
    s << indent << "linear_e: ";
    Printer<double>::stream(s, indent + "  ", v.linear_e);
    s << indent << "angle_e: ";
    Printer<double>::stream(s, indent + "  ", v.angle_e);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DATASHOW_MESSAGE_POSE_ERROR_H
